AWSTemplateFormatVersion: "2010-09-09"
Description: "Create database"
Parameters:
  VpcId:
    Type: String
    Description: Please add VPC ID created earlier
    Default: vpc-0b034769f60c8ee88
  SubnetId:
    Type: String
    Description: Please add Subnet in which to launch the web server
    Default: subnet-0cacf08b8d91eb53f
  AvailabilityZone:
    Type: String
    Description: Availability Zone into which instance will launch
    Default: us-east-1a
  DBInstanceIdentifier:
    Type: String
    Description: RDS instance identifier
  DBMasterUsername:
    Type: String
    Description: RDS username
  DBMasterPassword:
    Type: String
    NoEcho: true
    Description: RDS password

Resources:
  MyDBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId: !Ref VpcId
      DBSecurityGroupIngress:
        - EC2SecurityGroupName: !Ref MyEC2SecurityGroup
          EC2SecurityGroupOwnerId: !GetAtt MyEC2SecurityGroup.GroupOwner
        - CIDRIP: 0.0.0.0/0

  MyEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security group for EC2 instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: 0.0.0.0/0

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: "5.7"
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      VPCSecurityGroups:
        - !GetAtt MyDBSecurityGroup.GroupName
      AvailabilityZone: us-east-1a # Adjust this to your desired region and availability zone
      MultiAZ: false # Set to true if you want a Multi-AZ deployment
      StorageType: gp2
