AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an EC2 instance with Apache web server"

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # AWS Instance Type
      SecurityGroups:
        - !Ref WebAppSecurityGroup
      KeyName: WebAppKeyPair
      UserData:
       

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Allow HTTP from anywhere

Outputs:
  InstanceId:
    Description: "Instance ID"
    Value: !Ref WebAppInstance
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp